### ISSUE TITLE
Show Public pages in Private Zone

### ISSUE THREAD

**Issue by truck0321** [perak/kitchen-site#127]
I'd like to be able to display public zone menu items (in addition to the private_zone items) when a user logs in but the gui only lists private_zone pages in the private_zone section and my attempt to add public_zone menu items to the private_zone manually lists the public_zone item but clicking on it does nothing.  Duplicating pages in both zones is possible but bad practice.   Is this possible to do inside meteor kitchen?

**Comment by perak** [comment]
Hi @truck0321 what you need here is to move pages that should be accessible both from public and private zone into free zone. Docs is maybe unclear, but app can contain all three zones.

**Comment by perak** [comment]
I wrote last message from mobile phone, now writing from computer so I can give you more detailed explanation.

Example app using this concept is photosharing example: 

https://github.com/perak/kitchen-examples/tree/master/example-photosharing

In this example, main page (with shared images) is in `free_zone` and is accessible by all users (no matter logged-in or not).

`public_zone` contains pages that should be accessible to non-logged users only such as login and register form, forgot password etc. (for example, users that are logged in don't need register from).

`private_zone` contains pages that should be accessible to logged users only (change password, update profile).

Now, important things **if application contains pages inside all three zones**:

- You cannot have menu (or any other component) in free zone because in this case layout for free zone is not generated - only two layouts are generated - public and private.

- Because in this case free_zone doesn't have its menu, pages from free_zone should appear both in public_zone's menu and in private_zone's menu (as you can see in "photosharing" example).

I hope it's more clear now. 

And yes, I know - this should be included into docs :)

**Comment by perak** [comment]
Just to add simplified example showing setup with all three zones, so this issue can be used as documentation (until I add it to official docs)

```
{
	"application": {

		"free_zone": {
			"pages": [
				{
					"name": "home_free"
				}
			]
		},

		"public_zone": {

			"pages": [
				{
					"name": "login",
					"template": "login"
				},
				{
					"name": "register",
					"template": "register"
				}
			],

			"components": [
				{
					"name": "left_menu",
					"type": "menu",
					"items": [
						{
							"title": "Home", "route": "home_free"
						}
					]
				},
				{
					"name": "right_menu",
					"type": "menu",
					"items": [
						{
							"title": "Register", "route": "register"
						},
						{
							"title": "Login", "route": "login"
						}
					]
				}
			]
		},

		"private_zone": {
			"pages": [
				{
					"name": "user_settings"
				},
				{
					"name": "logout", "template": "logout"
				}
			],
			"components": [
				{
					"name": "left_menu",
					"type": "menu",
					"items": [
						{
							"title": "Home",
							"route": "home_free"
						}
					]
				},
				{
					"name": "right_menu",
					"type": "menu",
					"items": [
						{
							"title": "{{userEmail}}",
							"items": [
								{
									"title": "Settings",
									"route": "user_settings"
								},
								{
									"title": "Logout",
									"route": "logout"
								}
							]
						}
					]
				}
			]
		}
	}
}
```

- `home_free` is defined inside `free_zone` and is linked from both public_zone and private_zone menus.

- `login` and `register` are both defined and linked from `public_zone`

- `user_settings` and `logout` are both defined and linked from `private_zone`

That's it.

**Comment by truck0321** [comment]
Much clearer now, thank you!

**Comment by perak** [comment]
Solved, so... closing this issue.
