### ISSUE TITLE
Error at meteor startup with @import "{}/client/styles/framework/bootstrap3/custom.bootstrap.less

### ISSUE THREAD

**Issue by rodriced** [perak/kitchen-site#147]
Hello !
I have this error when i start meteor in kitchen (v0.9.51) generated projects (it seems for all examples I try) :

[[[[[ ~/WORK/METEOR/KITCHEN/Z ]]]]]           

=> Started proxy.                             
=> Started MongoDB.                           
=> Errors prevented startup:                  
   
   While processing files with less (for target web.browser):
   client/styles/styles/styles.less:1: Unknown import:
   {}/client/styles/framework/bootstrap3/custom.bootstrap.less**
   
=> Your application has errors. Waiting for file change.
=> Modified -- restarting.                    
=> Meteor server restarted                    
=> Started your app.

=> App running at: http://localhost:3000/

When I remove {} from '@import "{}/client/styles/framework/bootstrap3/custom.bootstrap.less";' in file client/styles/styles/styles.less, there is no more this error...

I don't know why because I didn't investigate very much but perhaps it can help...

**Comment by perak** [comment]
@rodriced error hapens only at first run (and if you wait little bit you'll see that meteor will restart and everything will work fine).

This is because imported file is created automatically on first run by nemo64:bootstrap package, but file is created after meteor realizes that file is missing. After file is created error doesn't happen anymore.

**Comment by rodriced** [comment]
@perak Ok thank's very much for the explanation !
