### ISSUE TITLE
Pagination on data views

### ISSUE THREAD

**Issue by markmitton** [perak/kitchen-site#269]
Hi

Can anyone tell me ho they are doing data table/view pagination using meteor-kitchen?

Thanks

**Comment by perak** [comment]
Sorry for late answer... maybe it still helps:

Meteor Kitchen will not produce code with pagination (not yet).

If you are doing "manually" (without meteor-kitchen) this is how:

Principle is:

1. Your publication should receive argument "pageNumber" and "pageSize", and query should skip & limit resultset like this: `someCollection.find({ ... }, { skip: pageNumber * pageSize, limit: pageSize, sort: { ... } }` (assuming pageNumber is 0-based).

2. Both on the client and on the server, query should be sorted by the same field and direction (or you'll get strange results).

3. Client side, in your subscription, you need to pass `pageNumber` (usually kept in the Session variable like this: `Meteor.subscribe("publicationName", Session.get("pageNumber"), pageSize)`.

4. Client side query should look exactly the same as at the server, but without "skip" argument, e.g.: `someCollection.find({ ... }, { limit: pageSize, sort: { ... } }`

5. Last thing, you need to update session variable pageNumber on user action (when user clicks "previous page" or "next page" button or if you are ambitious on scroll event. Because Session variable is reactive, your subscription and query will automatically re-run when you change pageNumber variable. e.g. code for next page is: `Session.set("pageNumber", (Session.get("pageNumber") || 0) + 1)` (ugly code says: get current page, if it's undefined then give me zero, and increase it by 1). :)

6. This will work but you'll need more: you need to know pageCount at the client so you can show/hide "next" button, but let's talk about "fine-tuning" later... :)
