### ISSUE TITLE
Gui 2

### ISSUE THREAD

**Issue by mttstt** [perak/kitchen-site#341]
Hi perak, thank for all.
When do you think the web gui 2.0 will be released ?

**Comment by perak** [comment]
Hi @mttstt :)

Currently working on a CLI (adding full support for react), and that goes slow because I'm busy with my everyday job... but looks like next week I'll have CLI with full support for react.

GUI is next step... don't know what to promise - I promised multiple times to multiple people and I miss what I promised so... I don't know really. It's 90 % done, need ~ 1week of coding to make it ready for deploy... but I don't have that 1 week of free time for coding...

**Comment by ajschmaltz** [comment]
I just found this project, used it & watched the video on your new GUI.  This is amazing, your work is so appreciated.  Whenever you get to finishing it, I'm sure it will be amazing.  The first $ I make with this tool will go straight to you.  THANK YOU.

**Comment by perak** [comment]
@mttst please e-mail me, I'll give you access to new gui

**Comment by perak** [comment]
@ajschmaltz too

**Comment by perak** [comment]
New GUI is released 2 weeks ago, so closing this issue. :)
