### ISSUE TITLE
Internal editor Files crashes build

### ISSUE THREAD

**Issue by jvp** [perak/kitchen-site#368]
When building a project, files that use _Internal editor_ end up in

> Copying files...
> Error in list of files to copy: copy_files[0].source file cannot be blank.

Also, is not not possible to upload a local files anymore? _External file_ only opts _Source file URL_

**Comment by perak** [comment]
@jvp in kitchen-gui, only files stored directly in .json (internal editor) and files uploaded to some url (external files) are supported.

That is not a bug, but intentional change.

To use files stored in your local computer (in computer where you are running the kitchen-cli) you can enter file url in format `file:// ... ` or you can run simple web server (like npm `http-server`) and enter file url's in format: `http://localhost:8080/...`.

**Comment by perak** [comment]
One more thing, please go to "Edit source" tab in kitchen GUI, and in the .json see `"copy_files": [ ... ]` array, your files should look like this:

```
		"copy_files": [
			{
				"source_content": "file content here",
				"dest": "OUTPUT_DIR/this_file_is_stored_in_json"
			},
			{
				"source": "http://url_to_the_file",
				"dest": "OUTPUT_DIR/this_is_external_file_at_url"
			}
		]
```

This is *not allowed:*

```
{
	"source_content": "file content here",
	"source": "http://url_to_the_file",
	"dest": "OUTPUT_DIR/this_is_external_file_at_url"
}
```

Please let me know if you succeed.

**Comment by perak** [comment]
Example how to use local file:

```
{
	"source": "file://path_to_the_local_file/myfile.jpg",
	"dest": "OUTPUT_DIR/myfile.jpg"
}
```

**Comment by perak** [comment]
Maybe I replied too much, but can be useful to someone else with the same problem:

1. be sure you are running latest version of `meteor-kitchen` CLI

2. be sure you click "Save" in the GUI before `running meteor-kitchen`

:)

**Comment by jvp** [comment]
Thanks again. Got it working with local files.
