### ISSUE TITLE
Return empty list when search String is empty in Data View

### ISSUE THREAD

**Issue by koernigo** [perak/kitchen-site#416]
Hi, I am trying to prevent that a list will be presented when the search string is empty in DataView. by default Data View displays the entire (uniltered) list.  I used to have a solution, but since the addition of the paging feature that doesn't work any more. Any pointer would be great!

Thanks!

**Comment by perak** [comment]
@koernigo try to set DataView's `search_engine_style` property to `true`. That will render big search box (and will not render any data) when search string is empty.

**Comment by koernigo** [comment]
@perak Thanks a lot, that worked well. Quick question: In some cases, manual code changes are necessary, even if I try to avoid them like the plague. I think there is a a way to use a code merge feature, but I could not find any details. Could you point me to something that explains how to set it up?

**Comment by perak** [comment]
Code merge is automatic - nothing to do, but... this is how it works:

By default, meteor kitchen creates git repository with two branches: “master” and “meteor-kitchen”. You can create more branches if you want and your manual code modifications can be done on any branch except on “meteor-kitchen” branch. So, ensure repo is on “master” (or whatever but not “meteor-kitchen”) and modify the code. Wheb you execute kitchen again, it will: commit your changes, switch to own branch, generate the code, commit, switch back to your branch, merge generated code with your code and exit (or report conflicts).

If during that gymnastics meteor-kitchen stops due to error, then it’s possible that it left repo on “meteor-kitchen” branch. If so, commit (or reset) and switch back to your branch manually.

**Comment by perak** [comment]
More related to code merging: pay attention to kitchen cli output: it prints in details what is happening with branches (at the beginning and at the end).

**Comment by koernigo** [comment]
@perak This works great.  I did have the repo set to meteor-kitchen, which is why the merge didn't work. Thank you also for the new tutorial video. There are a lot of little gems in there, like hiding the inactive buttons, creating reactive variables in lists etc.. Highly useful

**Comment by perak** [comment]
@koernigo closing this issue.
