### ISSUE TITLE
I can't seem to find the code for meteor-kitchen binary generator

### ISSUE THREAD

**Issue by shortweekend** [perak/kitchen-site#53]
I may be looking in the wrong repository, unless it's closed source. Thanks for any info.

**Comment by perak** [comment]
Hi, it's closed source. Do you want to contribute?

**Comment by shortweekend** [comment]
It's that I usually only use full open-source stacks. Thank you for clearing that up.

**Comment by vsivsi** [comment]
This is really unfortunate. I was about to try out meteor-kitchen for a new project, but I can't recommend that other people run a downloaded native binary with unknown contents that they can' t build themselves, unless it comes from a prominent source with an established reputation and transparent business model.

I mean no disrespect, your code is obviously yours to do with as you please, but Meteor is an open system, built on top of other open systems; all backed up by companies with service and support based business models. So, to me, using a closed system to generate the project code consumed by that stack just doesn't make a lot of sense, and seems unnecessarily risky (in multiple respects).

Anyway, best of luck to you, this seems like a cool project and it seems you're off to a good start technically speaking.

**Comment by vsivsi** [comment]
Just to add some friendly advice:  You really need to add a LICENSE to this github project, as well as making it clear what the license terms are for use of your closed downloaded native binary generator. You have a copyright notice in the generator console output and on the homepage footer that says "All rights reserved", and then give no permission or terms for use. I ended up in this issue because I couldn't find any license information anywhere, which is a huge red flag. Again, no disrespect intended, but from an institutional perspective none of what you've created is currently safe to use.

**Comment by perak** [comment]
@vsivsi thank you for advices. That will change soon - I am under negotiations with investor and meteor-kitchen will change a lot in near future, including license model. My advice is - stay tuned! :)
